### ISSUE TITLE
载入插件错误

### ISSUE THREAD

**Issue by CuteLittleSky** [TimeRainStarSky/Yunzai-genshin#5]
[TRSSYz][20:30:47.915][ERRO] 载入插件错误：genshin
[TRSSYz][20:30:47.916][ERRO] TypeError: segment.button is not a function
    at new sevenSaints (file:///D:/Yunzai/plugins/genshin/apps/sevenSaints.js:24:27)
    at file:///D:/Yunzai/lib/plugins/loader.js:69:24
    at D:\Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (D:\Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:3032:24)
    at D:\Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (D:\Yunzai\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js:9410:14)
    at PluginsLoader.load (file:///D:/Yunzai/lib/plugins/loader.js:65:16)
    at async Yunzai.run (file:///D:/Yunzai/lib/bot.js:119:5)

重新git clone也没用

**Comment by TimeRainStarSky** [comment]
```sh
git reset --hard
pnpm i
```
